# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Fixed scale used when autoscaling is disabled
replicaCount: 1

image:
  # -- Global image pullPolicy defined as default value when a container dont set
  # this value
  pullPolicy: IfNotPresent

containers:
  # -- Key will be used as name of containers and other resources like
  # configmaps, secrets or persistentVolumes. In this case **app** us used
  app:
    image:
      # -- Image to use for deploying
      repository: nginx
      # -- Image pullPolicy
      pullPolicy: IfNotPresent
      # -- Overrides the image tag whose default is the chart appVersion.
      tag: ""

    # -- We usually recommend not to specify default resources and to leave this as
    # a conscious choice for the user.
    resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

    # --Key value pairs created as environtment of container pod. This key has a
    # higher precedense than `config.env` and `config.secretEnv`. It allows gotpl
    # expressions.
    env: {}

    config:
      # --Key value pairs created using a ConfigMap and rendered as environment
      # variables inside container.Allows gotpl expressions, for example:
      # `MY_AWSOME_TPL_ENV_VAR: "{{ .Values.global.myAwesomeEnvVar }}"`
      env: {}
        # MY_AWESOME_ENV_VAR: "my awesome var"
        # MY_AWSOME_TPL_ENV_VAR: "{{ .Values.global.myAwesomeEnvVar }}"

      # --Sensitive Key value pairs created using a Secret and rendered as
      # environment variables inside container.Allows gotpl expressions, for
      # example: `MY_AWSOME_TPL_ENV_VAR: "{{ .Values.global.myAwesomeEnvVar }}"`
      secretEnv: {}
        # MY_SECRET_ENV_VAR: "supersecret"
        # MY_SECRET_TPL_ENV_VAR: "{{ .Values.global.superSecret }}"

    # -- Array of container ports. Each element can use fields as explained by
    # `kubectl explain pod.spec.containers[].ports`
    ports: []
    # - name: http
    #   containerPot: 8080
    #   protcolo: TCP
    persistence:
      # -- use a PVC to persist data
      enabled: false
      # -- the desired access modes the volume should have.
      accessModes:
        - ReadWriteOnce
      # -- Annotations to be added to the PersistentVolumeClaim
      annotations: {}
      # -- provide an existing PersistentVolumeClaim
      existingClaim: ""
      # -- Name of the StorageClass required by the claim.
      storageClassName: ""
      # -- represents the minimum and maximum resources the volume should have.
      resources: {}
      # -- Name for volume used inside pod volumes definition
      mountName: data
      # -- where volume should be mounted on. Required. For example: `/data`
      mountPath: ""
    # @ignored
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000

    # -- Define a custom
    # [livenessProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
    livenessProbe: {}
    # httpGet:
    #   path: /
    #   port: http

    # -- Define a custom
    # [readinessProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
    readinessProbe: {}
    # httpGet:
    #   path: /
    #   port: http

    # -- Define a custom
    # [startupProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
    startupProbe: {}
    # httpGet:
    #   path: /
    #   port: http

# --Array of objects, each one having key `name:` and value is a secretName.
# Allows gotpl expressions
imagePullSecrets: []
  # - name: "{{ .Values.global.regcred }}"
# @ignored
nameOverride: ""
# @ignored
fullnameOverride: ""

# @ignored
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# @ignored
podAnnotations: {}

# @ignored
podSecurityContext: {}
  # fsGroup: 2000


service:
  type: ClusterIP
  # -- Array of service ports. Each element can use fields as explained by
  # `kubectl explain service.spec.ports`
  ports: []
  #  - name: http
  #    protocol: TCP
  #    targetPort: http
  #    port: 8080

ingress:
  # -- Enable ingress or not
  enabled: false
  # -- IngressClass name
  className: ""
  # -- key value pairs for ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # Allows gotpl expressions. See example below
  # -- Array of objects, specifying `host:` and `paths:`. The last is an array
  # of key `path:` and value is the URI path
  hosts: []
      #    - host: "{{ .Values.global.ingress.host }}"
      #      paths:
      #        - path: "{{ default / .Values.global.ingress.path }}"
      #        - path: "{{ with (index .Values.global.paths 0) }}{{.}}{{- end -}}
      #          pathType: "{{ .Values.global.ingress.pathType }}"
      #    - host: chart-example.local
      #      paths:
      #        - path: /
      #          pathType: ImplementationSpecific

  # -- Array of objects, specifying `secretName:` and `hosts:`. The last is
  # an array of domains. Allows gotpl expressions
  tls: []
  #  - secretName: "{{ .Values.global.tls.secretName }}"
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  #      - "{{ .Values.global.tls.domain }}"


autoscaling:
  # -- Manage if HPA will be used for autoscaling
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# @ignored
nodeSelector: {}

# @ignored
tolerations: []

# @ignored
affinity: {}
