{{- $configSHA := include (print $.Template.BasePath "/configmap.yaml") . | sha256sum  -}}
{{- $secretSHA := include (print $.Template.BasePath "/secret.yaml") . | sha256sum -}}
{{ range $deploymentName, $deploymentValues := .Values.extraDeployments }}
{{- $volumesHolder := dict }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<CHARTNAME>.deploymentName" (dict "root" $ "deployment" $deploymentName) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
spec:
  {{- if not ( and $deploymentValues.autoscaling $deploymentValues.autoscaling.enabled ) }}
  replicas: {{ default 1 $deploymentValues.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "<CHARTNAME>.extraDeploymentSelectorLabels" (dict "root" $ "deployment" $deploymentName) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configSHA }}
        checksum/secret: {{ $secretSHA }}
      {{- with $deploymentValues.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "<CHARTNAME>.extraDeploymentSelectorLabels" (dict "root" $ "deployment" $deploymentName) | nindent 8 }}
    spec:
      {{- with (default $.Values.imagePullSecrets $deploymentValues.imagePullSecrets) }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "<CHARTNAME>.serviceAccountName" $ }}
      securityContext:
        {{- toYaml (default  $.Values.podSecurityContext $deploymentValues.podSecurityContext) | nindent 8 }}
      {{- with $deploymentValues.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- range $i, $container := $deploymentValues.containers }}
      - {{- include "<CHARTNAME>.containerManifest" (dict "root" $ "containerName" $i "container" $container "objectDescription" "Extra Deployment" "objectName"  (include "<CHARTNAME>.deploymentName" (dict "root" $ "deployment" $deploymentName)) "volumesHolder" $volumesHolder ) | nindent  10 }}
      {{- end }}
      {{- with $deploymentValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploymentValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploymentValues.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $volumesHolder $deploymentValues.extraVolumes }}
      volumes:
        {{- range $containers, $persistence := $volumesHolder }}
        {{- range $volName, $volSpec := $persistence }}
        - name: {{ $volName }}
          persistentVolumeClaim:
            claimName: {{ include "<CHARTNAME>.pvcName" (dict "root" $ "volumeName" $volName "volumeSpec" $volSpec) }}
        {{- end }}
        {{- end }}
        {{- range $deploymentValues.extraVolumes }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end }}