{{- $configSHA := include (print $.Template.BasePath "/configmap.yaml") . | sha256sum  -}}
{{- $secretSHA := include (print $.Template.BasePath "/secret.yaml") . | sha256sum -}}
{{ range $deploymentName, $deploymentValues := .Values.extraDeployments }}
{{- $volumesHolder := dict }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<CHARTNAME>.deploymentName" (dict "root" $ "deployment" $deploymentName) }}
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
spec:
  {{- if not ( and $deploymentValues.autoscaling $deploymentValues.autoscaling.enabled ) }}
  replicas: {{ default 1 $deploymentValues.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "<CHARTNAME>.extraDeploymentSelectorLabels" (dict "root" $ "deployment" $deploymentName) | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ $configSHA }}
        checksum/secret: {{ $secretSHA }}
      {{- with $deploymentValues.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "<CHARTNAME>.extraDeploymentSelectorLabels" (dict "root" $ "deployment" $deploymentName) | nindent 8 }}
    spec:
      {{- with (default $.Values.imagePullSecrets $deploymentValues.imagePullSecrets) }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "<CHARTNAME>.serviceAccountName" $ }}
      securityContext:
        {{- toYaml (default  $.Values.podSecurityContext $deploymentValues.podSecurityContext) | nindent 8 }}
      {{- with $deploymentValues.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- range $i, $container := $deploymentValues.containers }}
        - name: {{ include "<CHARTNAME>.containerName" (dict "prefix" $deploymentName "container" $i) }}
          securityContext:
            {{- toYaml ( default dict $container.securityContext ) | nindent 12 }}
          image: "{{ required (printf "extra Deployment %s.containers.%s.image is required" $deploymentName $i) ( required (printf "extra Deployment %s.containers.%s.image.repository is required" $deploymentName $i) $container.image).repository }}:{{ $container.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ default $.Values.image.pullPolicy $container.image.pullPolicy }}
          {{- if $container.env }}
          env:
            {{- range $key, $val := $container.env }}
            - name: {{ $key }}
              value: {{ tpl $val $ | quote }}
            {{- end }}
          {{- end }}
          {{- if and $container.config (or $container.config.env $container.config.secretEnv $container.extraEnvFrom) }}
          envFrom:
            {{- if or $container.config.env }}
            - configMapRef:
                name: {{ include "<CHARTNAME>.containerObjectName" (dict "root" $ "container" (include "<CHARTNAME>.containerName" (dict "prefix" $deploymentName "container" $i))) }}
            {{- end }}
            {{- if $container.config.secretEnv }}
            - secretRef:
                name: {{ include "<CHARTNAME>.containerObjectName" (dict "root" $ "container" (include "<CHARTNAME>.containerName" (dict "prefix" $deploymentName "container" $i))) }}
            {{- end }}
            {{- if $container.extraEnvFrom }}
            {{- toYaml $container.extraEnvFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with $container.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.command }}
          command:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.args }}
          args:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.livenessProbe }}
          livenessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.readinessProbe }}
          readinessProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with $container.startupProbe }}
          startupProbe:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml ( default dict $container.resources ) | nindent 12 }}
          {{- if $container.persistence }}
          {{- $_ := set $volumesHolder $i $container.persistence -}}
          {{- end }}
          {{- if or $container.persistence $container.extraVolumeMounts }}
          volumeMounts:
            {{- range $volName, $volSpec := $container.persistence }}
            - name: {{ $volName }}
              mountPath: {{ required (printf "containers[%d].persistence.%s.mountPath must be set" $i $volName) $volSpec.mountPath }}
            {{- end }}
            {{- range $extraMount := $container.extraVolumeMounts }}
            - {{ toYaml $extraMount | nindent 14 }}
            {{- end }}
          {{- end }}
      {{- end }}
      {{- with $deploymentValues.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploymentValues.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $deploymentValues.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $volumesHolder $deploymentValues.extraVolumes }}
      volumes:
        {{- range $containers, $persistence := $volumesHolder }}
        {{- range $volName, $volSpec := $persistence }}
        - name: {{ $volName }}
          persistentVolumeClaim:
            claimName: {{ include "<CHARTNAME>.pvcName" (dict "root" $ "volumeName" $volName "volumeSpec" $volSpec) }}
        {{- end }}
        {{- end }}
        {{- range $deploymentValues.extraVolumes }}
        - {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end }}